### ISSUE TITLE
URL da Prefeitura alterada

### ISSUE THREAD

**Issue by gustavodini** [pablopdomingos/nfse#12]
Oi Pablo, uso sua lib a um tempo em um projeto meu e a Prefeitura de BH alterou as URLs de homologação e produção no mês de fevereiro de 2024:

![Captura de tela de 2024-03-18 20-51-30](https://github.com/pablopdomingos/nfse/assets/16492447/5ea5f0fe-81ed-4d43-ba54-14b11d14b4a3)

Tenho uma branch pronta já com as alterações. Se conseguir me liberar consigo fazer um PR para uma nova versão da lib. Aguardo!

**Comment by pablopdomingos** [comment]
#13 - Links alterados
