### ISSUE TITLE
Dúvida - Geração de Cadeia de certificados

### ISSUE THREAD

**Issue by yurikilian** [pablopdomingos/nfse#6]
Pablo! Parabéns pela iniciativa! Teu código é muito limpo e de fácil compreensão!

Cara, vou fazer fork do teu trabalho para implementar uma solução de nota fiscal aqui pra Porto Alegre - RS e eu gostaria de saber mais informações à respeito da geração da cadeia de certificados. Sabe me dizer em qual documento de referência / bibliografia eu acho isto?

Quero entender porque preciso gerar esta cadeia antes de fazer o envio. 

Muito obrigado!

**Comment by pablopdomingos** [comment]
Boa tarde Yuri,

Acredito que apenas alterando os links das linhas 25 e 26 do arquivo [NFSeGeraCadeiaCertificados.java](https://github.com/pablopdomingos/nfse/blob/master/nfse-bh/src/main/java/com/pablodomingos/util/NFSeGeraCadeiaCertificados.java) para o endereço da prefeitura de POA resolverá seu problema.

**Comment by pablopdomingos** [comment]
Sobre o cacerts esse [artigo](http://devbrasil.net/group/nfce-em-java/page/como-o-java-trabalha-com-certificados-digitais) explica o funcionamento
